### LOGIN
POST http://localhost:3000/login
content-type: application/json

{
    "username": "username",
    "password": "password"
}

### LOGGED
GET http://localhost:3000/logged

### CREATE NEW USER WITH AUTO LOGIN
POST http://localhost:3000/signup
content-type: application/json

{
    "username":"username", 
    "password":"password"
}

### BAD LOGIN TEST
POST http://localhost:3000/login
content-type: application/json

{
    "username": "invalid",
    "password": "login"
}

### LOGOUT
GET http://localhost:3000/logout
